version: 2

build:
  image: latest

formats: all

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
