---
branch: master

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: ./ci-scripts/bump-python-version.sh ${nextRelease.version}
      publishCmd: ./ci-scripts/pypi-release.sh
  - - "@semantic-release/git"
    - assets:
        - "lambda_handlers/version.py"
        - "CHANGELOG.md"
  - - "@semantic-release/github"
    - assets:
        - "dist/*"
