---
branch: master

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: |-
        echo "__version__ = '${nextRelease.version}'" > lambda_handlers/version.py
  - - "@semantic-release/git"
    - assets:
        - "lambda_handlers/version.py"
        - "CHANGELOG.md"
  - - "@semantic-release/github"
    - assets:
      - "dist/*"
