dist: xenial
language: python
os:
  - linux
python:
  - "3.7"
install:
  - pip install -U pip setuptools
  - pip install pipenv
  - pipenv install --dev
  - pipenv run python setup.py develop
script:
  - tox -e lint
  - tox -e isort
  - tox -e mypy
  - tox -e tests
deploy:
  - provider: script
    script: ci-scripts/release.sh
    on:
      branch: master
