language: python
python:
  - "3.7"

install:
  - pip install -U pip setuptools
  - pip install pipenv
  - pipenv install --dev
  - pipenv run python setup.py develop

script: |
  set -e
  pipenv run pytest
deploy:
  - provider: pypi
    twine_version: 1.12.1
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: 3.6
      repo: enter-at/lambda-handlers
    user: enterat
    password:
      secure: xxx
