dist: xenial
language: python
python:
- '3.7'
install:
- pip install -U pip setuptools
- pip install pipenv
- pipenv install --dev
- pipenv run python setup.py develop
script:
- tox -e lint
- tox -e isort
- tox -e mypy
deploy:
- provider: pypi
  distributions: sdist 
  user: $TEST_PYPI_USER
  password: $TEST_PYPI_PASS
  server: https://test.pypi.org/legacy/
  on:
    tags: true
    python: '3.7'
    repo: enter-at/lambda-handlers
